AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito group and policy

Resources:
  AccountsCognitoGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: accounts-cognito-group
      Policies:
        - PolicyName: accounts-cognito-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:List*
                  - cognito-idp:Create*
                Resource: "*"
