AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito group and policy

Resources:
  AccountsCognitoGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: accounts-cognito-group
      Policies:
        - PolicyName: accounts-cognito-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:List*
                  - cognito-idp:Create*
                Resource: "*"
              - Effect: Allow
                Action:
                  - cognito-idp:Describe*
                  - cognito-idp:Get*
                  - cognito-idp:Update*
                  - cognito-idp:Delete*
                  - cognito-idp:Add*
                Resource: "*"
                Condition:
                  StringEquals:
                    "aws:ResourceTag/user": "${aws:PrincipalTag/user}"
